version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: healthcare-postgres
    restart: always
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    container_name: healthcare-app-dev
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: mvn spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/healthcare_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
